default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default

development:
  <<: *default
  database: mimir_project_development

test:
  <<: *default
  database: mimir_project_test

production:
  <<: *default
  database: mimir_project_production
